spring:
  application:
    name: board
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mariadb://localhost:3306/board
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 1095593
            client-secret: kNCuOSJq9N0jNhiyXuiEecjVEMNJL3EJ
            redirect-uri: "https://localhost:8080/kakao/callback"
            authorization-grant-type: authorization_code
            scope: profile
            client-name: 4weekSpring
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  expiration_time: 86400000
  secret: kNCuOSJq9N0jNhiyXuiEecjVEMNJL3EJ
  refresh_token_expiration_time: 126000000

