spring:
  application:
    name: board
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mariadb://localhost:3306/board


jwt:
  expiration_time: 86400000
  secret: mySuperSecretKeyForJwtToken12345!
  refresh_token_expiration_time: mySuperSecretKeyForJwtToken54321!

